name: Deploy to DigitalOcean

on:
    push:
        branches:
            - master

jobs:
    deploy:
        name: Deploy Application
        runs-on: ubuntu-latest

        steps:
            # 1️⃣ - Récupérer le code
            - name: Checkout repository
              uses: actions/checkout@v3

            # 2️⃣ - Configurer Node.js
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'  # Adapte si besoin


            # 🔐 Générer le fichier .env avec les clés Firebase
            - name: Generate .env file
              run: |
                  echo "VITE_FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY }}" >> .env
                  echo "VITE_FIREBASE_AUTH_DOMAIN=${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}" >> .env
                  echo "VITE_FIREBASE_PROJECT_ID=${{ secrets.VITE_FIREBASE_PROJECT_ID }}" >> .env
                  echo "VITE_FIREBASE_STORAGE_BUCKET=${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}" >> .env
                  echo "VITE_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}" >> .env
                  echo "VITE_FIREBASE_APP_ID=${{ secrets.VITE_FIREBASE_APP_ID }}" >> .env
                  echo "VITE_FIREBASE_MEASUREMENT_ID=${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}" >> .env
                  echo "VITE_OPENAI_API_KEY=${{ secrets.VITE_OPENAI_API_KEY }}" >> .env
                  echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env

            # 📤 Déployer le fichier .env
            - name: Deploy .env to DigitalOcean
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ secrets.SERVER_IP }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  source: ".env"
                  target: "/var/www/GastonApp"
# 4️⃣ - Installer les dépendances
            - name: Install dependencies
              run: npm install

            # 5️⃣ - Construire l'app
            - name: Build project
              run: npm run build

            # 6️⃣ - Déployer les fichiers buildés sur le serveur
            - name: Deploy to DigitalOcean
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ secrets.SERVER_IP }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  source: "dist/*"
                  target: "/var/www/GastonApp"

            # 7️⃣ - Redémarrer Nginx
            - name: Restart Nginx
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ secrets.SERVER_IP }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      sudo systemctl restart nginx
