name: Deploy to DigitalOcean

on:
    push:
        branches:
            - master

jobs:
    deploy:
        name: Deploy Application
        runs-on: ubuntu-latest

        steps:
            # 1️⃣ - Récupérer le code
            - name: Checkout repository
              uses: actions/checkout@v3

            # 2️⃣ - Configurer Node.js
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'  # Adapte si besoin

            # 3️⃣ - Générer le fichier .env avec les clés Firebase et OpenAI
            -   name: Generate .env file
                run: |
                    cat <<EOF > .env
                    VITE_FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}
                    VITE_FIREBASE_AUTH_DOMAIN=${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
                    VITE_FIREBASE_PROJECT_ID=${{ secrets.VITE_FIREBASE_PROJECT_ID }}
                    VITE_FIREBASE_STORAGE_BUCKET=${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
                    VITE_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
                    VITE_FIREBASE_APP_ID=${{ secrets.VITE_FIREBASE_APP_ID }}
                    VITE_FIREBASE_MEASUREMENT_ID=${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}
                    VITE_OPENAI_API_KEY=${{ secrets.VITE_OPENAI_API_KEY }}
                    EOF

# 4️⃣ - Installer les dépendances
            - name: Install dependencies
              run: npm install

            # 5️⃣ - Construire l'app
            - name: Build project
              run: npm run build

            # 6️⃣ - Déployer les fichiers buildés sur le serveur
            - name: Deploy to DigitalOcean
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ secrets.SERVER_IP }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  source: "dist/*"
                  target: "/var/www/GastonApp"

            # 7️⃣ - Redémarrer Nginx
            - name: Restart Nginx
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ secrets.SERVER_IP }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      sudo systemctl restart nginx
